### ISSUE TITLE
Load existing run context

### ISSUE THREAD

**Issue by Nintorac** [sigopt/sigopt-python#345]
Hi, 

I am trying to run an experiment that sends tasks to a cluster to execute.

I am passing through the `run_id` to be loaded on the remote instance but can't figure out how to get the existing run as a context object from the id.

My script looks a little like this

```
import sigopt
import remote_client

remote_client.execute(sigopt.get_run_id(), sigopt.params)
```

and run the experiment like this

`sigopt optimize -e experiment.yml python run_and_track_in_sigopt.py`

On the remote side I am picking up the `run_id` like this

```
        def start_run():
            if controller.run_id is not None:
                return sigopt.get_run(controller.run_id)
            return sigopt.create_run()

        with start_run() as run:
            run.set_parameters(controller.persistor.model_config)
            
            result = f(controller, *args)
            if result is not None:
                run.log_metrics(result)
            else:
                run.log_failure()
```

but this crashes with the following

```
server_1  | 2022-03-06 23:09:41,223 - ServerRunner - INFO - [run=1]: Workflow scatter_and_gather (<class 'sepsis_model.sigopt_workflow.SigOptScatterAndGather'>) started
server_1  | 2022-03-06 23:09:41,771 - ServerRunner - ERROR - [run=1, wf=scatter_and_gather]: exception in workflow scatter_and_gather
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.8/site-packages/nvflare/private/fed/server/server_runner.py", line 98, in _execute_run
server_1  |     wf.responder.control_flow(self.abort_signal, fl_ctx)
server_1  |   File "/workspace/run_1/app_server/custom/sepsis_model/sigopt_workflow.py", line 44, in wrapper
server_1  |     with start_run() as run:
server_1  | AttributeError: __enter__
```

Is there a way to load the run as a contextable object or is there a better approach to what I'm trying to do?

Thanks!

**Comment by Nintorac** [comment]
I was able to get the run context like so

```
conn = Connection()
run = sigopt.get_run(controller.run_id)                
context = RunContext(conn, run)
```
