### ISSUE TITLE
Ray Integration serialisation issues

### ISSUE THREAD

**Issue by Nintorac** [sigopt/sigopt-python#362]
I have also created an issue about this in the Ray repository  - https://github.com/ray-project/ray/issues/24864

I have further encountered an issue where if the search space is not correctly configured this results in an exception in the ray cluster but the exception is not serializable as well and  results in the difficult to debug error below

```
HYDRA_FULL_ERROR=1 python tune_runner.py 

2022-05-23 12:38:12,850 INFO packaging.py:388 -- Creating a file package for local directory '/home/oliver/datarwe/sepsis_experiments'.
2022-05-23 12:38:12,867 INFO packaging.py:241 -- Pushing file package 'gcs://_ray_pkg_26cf3e865909e26a.zip' (0.46MiB) to Ray cluster...
2022-05-23 12:38:13,498 INFO packaging.py:243 -- Successfully pushed file package 'gcs://_ray_pkg_26cf3e865909e26a.zip'.
Failed to unpickle serialized exception
Error executing job with overrides: []
Traceback (most recent call last):
  File "tune_runner.py", line 155, in <module>
    main()
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "tune_runner.py", line 49, in main
    ray.get(remote_tune.remote(config))
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/ray/util/client/api.py", line 43, in get
    return self.worker.get(vals, timeout=timeout)
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/ray/util/client/worker.py", line 433, in get
    res = self._get(to_get, op_timeout)
  File "/home/oliver/miniconda3/envs/nvflare/lib/python3.8/site-packages/ray/util/client/worker.py", line 461, in _get
    raise err
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/exceptions.py", line 38, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: __init__() missing 1 required positional argument: 'status_code'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/serialization.py", line 332, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/opt/conda/lib/python3.8/site-packages/ray/serialization.py", line 258, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/opt/conda/lib/python3.8/site-packages/ray/exceptions.py", line 32, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/opt/conda/lib/python3.8/site-packages/ray/exceptions.py", line 41, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
```

in my case the above exception was caused by a misconfigured  search space from this yaml

```yaml

search_space:
  search_space:
  - name: experiment.lr
    type: double
    bounds:
      max: 0.1
      min: 0.0001
  - name: experiment.model.config.hidden_features
    type: int
    bounds:
      min: 4
      max: 9
```
note: the double nested `search_space`

**Comment by tjs-intel** [comment]
Hi @Nintorac, thank you for reporting the issue. The SigOpt integration for Ray is managed by the Ray Project at https://github.com/ray-project/ray

**Comment by Nintorac** [comment]
Of course, looks like I opened the issue there as well.

Looking at this I think my reasoning to open here is due to sigopt is throwing non-serializable exceptions. My assumption was fixing this would require work on this side :)

**Comment by Nintorac** [comment]
Happy to consider diving into this. Does Intel provide bounties or rewards for this kind of work?

**Comment by tjs-intel** [comment]
I am not aware of any bounties for contributions, other than for security findings. You can read about Intel's bug bounty program here: https://www.intel.com/content/www/us/en/security-center/bug-bounty-program.html
