### ISSUE TITLE
No requirements.txt file that is referenced in setup.py in the tarball for sigopt

### ISSUE THREAD

**Issue by yurivict** [sigopt/sigopt-python#439]
[This tarball](https://files.pythonhosted.org/packages/source/s/sigopt/sigopt-8.8.2.tar.gz) contains setup.py, which references requirements.txt. However, requirements.txt doesn't exist in that tarball.

**Comment by tjs-intel** [comment]
@yurivict Thank you for reporting the issue! Can you please describe in more detail the problem you are encountering? When we publish the package to PyPI the requirements seems to be captured since `pip install sigopt==8.8.2` installs all the necessary requirements.

**Comment by yurivict** [comment]
pip downloads the pre-built .whl file so it succeeds.

But the FreeBSD port uses the sourse tarball and fails to build it because of the missing file:
```
===>  License MIT accepted by the user
===>   py39-sigopt-8.8.2 depends on file: /usr/local/sbin/pkg - found
===> Fetching all distfiles required by py39-sigopt-8.8.2 for building
===>  Extracting for py39-sigopt-8.8.2
=> SHA256 Checksum OK for sigopt-8.8.2.tar.gz.
===>  Patching for py39-sigopt-8.8.2
===>   py39-sigopt-8.8.2 depends on package: py39-setuptools>0 - found
===>   py39-sigopt-8.8.2 depends on package: py39-wheel>0 - found
===>   py39-sigopt-8.8.2 depends on file: /usr/local/bin/python3.9 - found
===>   py39-sigopt-8.8.2 depends on package: py39-build>=0 - found
===>   py39-sigopt-8.8.2 depends on package: py39-installer>=0 - found
===>   py39-sigopt-8.8.2 depends on file: /usr/local/bin/ccache - found
===>  Configuring for py39-sigopt-8.8.2
===>  Building for py39-sigopt-8.8.2
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 31, in <module>
    with open(os.path.join(here, "requirements.txt")) as requirements_fp:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/ports/misc/py-sigopt/work-py39/sigopt-8.8.2/requirements.txt'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
*** Error code 1
```

**Comment by tjs-intel** [comment]
This should now be resolved. Please re-open if you still encounter an issue @yurivict 

`pip install --no-binary sigopt sigopt==8.8.3`
